### ISSUE TITLE
Can't add move in the opening builder

### ISSUE THREAD

**Issue by alexandru-duca** [marcusbuffett/chessmadra-frontend#8] opened 2022-09-03 23:49 UTC
I created the following repertoire: [white.txt](https://github.com/marcusbuffett/chessmadra-frontend/files/9483556/white.txt)
I'd like to add "3... Nxe4 4.Nxe4" to the existing line "1.d4 d5 2.e4 Nf6 3.Nc3", but this doesn't work.

**Comment by marcusbuffett** [comment] 2022-09-04 11:12
Thanks for the report! Appreciate the detailed steps too, been seeing this error in the logs but haven't been able to reproduce it. Will look into it and have a fix sometime today

**Comment by marcusbuffett** [comment] 2022-09-04 13:11
Huh I actually can't reproduce the error. I do see that the moves don't get shown on the right-hand side, which I just fixed. But playing out the line on the board and adding still works. Does this line up with what you saw, or did you play the moves on the board and saving still didn't work after that?

**Comment by alexandru-duca** [comment] 2022-09-04 18:30
I should have gone into more detail. Here are the steps to reproduce the error:

1. Open [Chessmadra's opening builder](https://chessmadra.com/openings).
2. You are asked how to create your opening. Select "Import".
3. Press the "+ White Openings" Button and import a pgn file with the following content: `1. d4 f5 (1... d5 2. e4 dxe4 (2... e6 3. Nc3 Nf6 (3... dxe4 4. Nxe4) 4. e5)  (2... c6 3. Nc3)  (2... Nf6 3. Nc3) 3. Nc3 e6 (3... Nf6 4. f3 exf3 5. Nxf3 Bg4 (5... e6 6. Bg5 Be7 7. Bd3) 6. h3)  (3... c6 4. f3)  (3... f5 4. Bg5))  (1... Nf6 2. Nc3 d5 (2... g6 3. e4 d6 (3... Bg7 4. e5 Ng8 5. Bc4) 4. Bg5 Bg7 5. e5 dxe5 6. dxe5 Qxd1+ 7. Rxd1)  (2... e6 3. e4)  (2... c5 3. d5 d6 4. e4) 3. e4)  (1... e6 2. e4)  (1... c5 2. d5 d6 3. Nc3)  (1... g6 2. e4 Bg7 3. Nc3 d6 4. Bg5)  (1... c6 2. e4)  (1... d6 2. e4 Nf6 3. Nc3)  (1... e5 2. dxe5 Nc6 3. Nf3) 2. e4`
4. Press the "Settings" button and choose the elo range "1900-2800". The "biggest gap" position for White is now the following fen: `rnbqkb1r/ppp1pppp/8/3p4/3Pn3/2N5/PPP2PPP/R1BQKBNR w KQkq - 0 4`
5. Click on the board in order to enter your response to the "biggest gap" position.
6. Choose "4.Nxe4".
7. Press "Save to repertoire" on the down right of your screen.

The problem now is that the "Save to repertoire" doesn't save the move "4.Nxe4".

**Comment by marcusbuffett** [comment] 2022-09-04 20:19
Wow, dream bug report right there, thanks for all the detail, I'll see if I can reproduce it now

**Comment by alexandru-duca** [comment] 2022-09-04 23:24
Pressing the "Save to repertoire" button after the following the above steps sends out the following curl (I removed identifiying data) to your api:
```
curl --request POST \
  --url https://chessmadra.com/api/v1/openings/add_moves \
  --data '{"moves":[{"epd":"rnbqkb1r/ppp1pppp/5n2/3p4/3PP3/2N5/PPP2PPP/R1BQKBNR b KQkq -","epd_after":"rnbqkb1r/ppp1pppp/8/3p4/3Pn3/2N5/PPP2PPP/R1BQKBNR w KQkq -","san_plus":"Nxe4","side":"white","pending":true,"mine":false,"srs":{"needs_review":false,"first_review":false}},{"epd":"rnbqkb1r/ppp1pppp/8/3p4/3Pn3/2N5/PPP2PPP/R1BQKBNR w KQkq -","epd_after":"rnbqkb1r/ppp1pppp/8/3p4/3PN3/8/PPP2PPP/R1BQKBNR b KQkq -","san_plus":"Nxe4","side":"white","pending":true,"mine":true,"srs":{"needs_review":false,"first_review":false}}],"side":"white","replace":false}'
```
The server response is always `500 Internal Server Error` with the following payload:
```
Diesel error: DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"pk_repertoire_moves_v2\"")
```
Maybe this helps you while debugging.

**Comment by marcusbuffett** [comment] 2022-09-05 10:44
This is now fixed! Very tricky bug actually. On the backend when you add a move, it will check if there are any moves in any of the positions in your repertoire that will transpose to a position you already know. This is so that the UI won't say your biggest miss is a position that you've already got a response to.  With the PGN that was uploaded, there were two different paths to get to the same position that then had a transposition back to a covered position. So it was trying to add the same move twice, which just errored out since the moves have to be unique. The reason it was so hard to debug was because the logic to find the transposition moves only looked at the cached opening lines, not the database, so it would only happen if you (or someone else) had looked at that line, which would fill in the cache. So this ended up being a two-for-one: fix the transposition-finding logic, and fix the adding moves logic to not error out on duplicates.

Thanks so much for the detailed bug report, I had seen a bunch of people running into that 500 in the logs but I couldn't crack it.

**Closed by marcusbuffett** 2022-09-05 10:44 UTC
